spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1/sso_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    url: jdbc:mysql://124.202.166.173:31008/tera_dev_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true&useSSL=false
    username: root
    password: n1cetest
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: never
    continue-on-error: true
    platform: dev-aaaa
    hikari:
      max-lifetime: 500000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    mongodb:
      uri: mongodb://124.202.166.173:31588/demo
    cassandra:
      keyspace-name: system
      #entity-base-packages:
      contact-points: 124.202.166.173
      port: 30890
      session-name: Test Cluster
      local-datacenter: datacenter1 #默认的数据中心
